In [ ]:
# 이 파일은 예시용으로 작성된 것이며, 실제 개발 시 삭제해도 됩니다.
# VS Code에서도 .ipynb 확장자로 파일을 생성하면 주피터 기능을 그대로 활용할 수 있습니다.
# .py 파일로 AI 개발을 진행하는 건 비효율적일 것 같아서 AI 개발자분들은 참고하길 바랍니다!

In [ ]:
import pandas as pd

fish = pd.read_csv("https://bit.ly/fish_csv_data")


[[242.      25.4     30.      11.52     4.02  ]
 [290.      26.3     31.2     12.48     4.3056]
 [340.      26.5     31.1     12.3778   4.6961]
 [363.      29.      33.5     12.73     4.4555]
 [430.      29.      34.      12.444    5.134 ]]


In [3]:
# 어떤 종류의 생선이 있는지 출력
print(pd.unique(fish["Species"]))

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']


In [4]:
# 입력 데이터 지정
fish_input = fish[["Weight", "Length", "Diagonal", "Height", "Width"]].to_numpy()
print(fish_input[:5])

[[242.      25.4     30.      11.52     4.02  ]
 [290.      26.3     31.2     12.48     4.3056]
 [340.      26.5     31.1     12.3778   4.6961]
 [363.      29.      33.5     12.73     4.4555]
 [430.      29.      34.      12.444    5.134 ]]
